<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260913232044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE affectations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE affectations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE affectations ALTER role DROP DEFAULT');
        $this->addSql('ALTER TABLE affectations ALTER date_affectation DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_affectations_projet RENAME TO IDX_4209104C18272');
        $this->addSql('ALTER INDEX idx_affectations_membre RENAME TO IDX_42091046A99F74A');
        $this->addSql('DROP INDEX idx_membres_email');
        $this->addSql('ALTER TABLE membres ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE membres ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE membres ALTER avatar_url DROP DEFAULT');
        $this->addSql('ALTER TABLE membres ALTER roles TYPE JSON');
        $this->addSql('ALTER TABLE membres ALTER roles DROP DEFAULT');
        $this->addSql('ALTER TABLE membres ALTER date_creation DROP DEFAULT');
        $this->addSql('ALTER INDEX membres_email_key RENAME TO UNIQ_594AE39CE7927C74');
        $this->addSql('DROP INDEX idx_notifications_membre_lu');
        $this->addSql('ALTER TABLE notifications ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER date_creation DROP DEFAULT');
        $this->addSql('DROP INDEX idx_projets_code');
        $this->addSql('ALTER TABLE projets ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE projets ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE projets ALTER date_creation DROP DEFAULT');
        $this->addSql('ALTER INDEX projets_code_key RENAME TO UNIQ_B454C1DB77153098');
        $this->addSql('ALTER TABLE sessions_travail ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE sessions_travail ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE sessions_travail ALTER debut DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_sessions_tache RENAME TO IDX_BA88A19D2235D39');
        $this->addSql('ALTER INDEX idx_sessions_membre RENAME TO IDX_BA88A196A99F74A');
        $this->addSql('DROP INDEX idx_taches_statut');
        $this->addSql('ALTER TABLE taches ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE taches ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE taches ALTER priorite DROP DEFAULT');
        $this->addSql('ALTER TABLE taches ALTER statut DROP DEFAULT');
        $this->addSql('ALTER TABLE taches ALTER temps_estime DROP DEFAULT');
        $this->addSql('ALTER TABLE taches ALTER date_creation DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_taches_projet RENAME TO IDX_3BF2CD98C18272');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE affectations ALTER id SET DEFAULT nextval(\'affectations_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE affectations ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE affectations ALTER role SET DEFAULT \'MEMBRE\'');
        $this->addSql('ALTER TABLE affectations ALTER date_affectation SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX idx_4209104c18272 RENAME TO idx_affectations_projet');
        $this->addSql('ALTER INDEX idx_42091046a99f74a RENAME TO idx_affectations_membre');
        $this->addSql('ALTER TABLE membres ALTER id SET DEFAULT nextval(\'membres_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE membres ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE membres ALTER avatar_url SET DEFAULT \'\'');
        $this->addSql('ALTER TABLE membres ALTER date_creation SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE membres ALTER roles TYPE JSONB');
        $this->addSql('ALTER TABLE membres ALTER roles SET DEFAULT \'["ROLE_USER"]\'');
        $this->addSql('CREATE INDEX idx_membres_email ON membres (email)');
        $this->addSql('ALTER INDEX uniq_594ae39ce7927c74 RENAME TO membres_email_key');
        $this->addSql('ALTER TABLE notifications ALTER id SET DEFAULT nextval(\'notifications_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notifications ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER date_creation SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_notifications_membre_lu ON notifications (membre_id, lu)');
        $this->addSql('ALTER TABLE projets ALTER id SET DEFAULT nextval(\'projets_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE projets ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE projets ALTER date_creation SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_projets_code ON projets (code)');
        $this->addSql('ALTER INDEX uniq_b454c1db77153098 RENAME TO projets_code_key');
        $this->addSql('ALTER TABLE sessions_travail ALTER id SET DEFAULT nextval(\'sessions_travail_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE sessions_travail ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE sessions_travail ALTER debut SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX idx_ba88a19d2235d39 RENAME TO idx_sessions_tache');
        $this->addSql('ALTER INDEX idx_ba88a196a99f74a RENAME TO idx_sessions_membre');
        $this->addSql('ALTER TABLE taches ALTER id SET DEFAULT nextval(\'taches_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE taches ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE taches ALTER priorite SET DEFAULT \'MOYENNE\'');
        $this->addSql('ALTER TABLE taches ALTER statut SET DEFAULT \'A_FAIRE\'');
        $this->addSql('ALTER TABLE taches ALTER temps_estime SET DEFAULT 0');
        $this->addSql('ALTER TABLE taches ALTER date_creation SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_taches_statut ON taches (statut)');
        $this->addSql('ALTER INDEX idx_3bf2cd98c18272 RENAME TO idx_taches_projet');
    }
}
